# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: stanislaw.malinowski@diamond.ac.uk
author_name: Stanislaw Malinowski
component_owner: group:default/daq
description: Plans and devices for the DLS beamline i18
distribution_name: i18-bluesky
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: i18_bluesky
pypi: true
repo_name: i18-bluesky
type_checker: pyright
